"""Généré par tools/generate_python_sdk.py — ne pas éditer."""

from types import MappingProxyType
from typing import Mapping

from .models import Operation

CONTRACT_VERSION = '1.0.0'

_OPERATIONS = {
    'delete_api_conversations_by_conv_id': Operation(
        operation_id='delete_api_conversations_by_conv_id',
        method='DELETE',
        path='/api/conversations/{conv_id}',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversation Delete',
    ),
    'delete_api_dnd': Operation(
        operation_id='delete_api_dnd',
        method='DELETE',
        path='/api/dnd',
        auth='session',
        tag='dnd',
        summary='Api Dnd Disable',
    ),
    'delete_api_food_cart_by_plan_id': Operation(
        operation_id='delete_api_food_cart_by_plan_id',
        method='DELETE',
        path='/api/food/cart/{plan_id}',
        auth='session',
        tag='food',
        summary='Api Food Cart Cancel',
    ),
    'delete_api_food_session_capture': Operation(
        operation_id='delete_api_food_session_capture',
        method='DELETE',
        path='/api/food/session/capture',
        auth='session',
        tag='food',
        summary='Api Food Session Capture Stop',
    ),
    'delete_api_life_profile_by_entry_id': Operation(
        operation_id='delete_api_life_profile_by_entry_id',
        method='DELETE',
        path='/api/life-profile/{entry_id}',
        auth='session',
        tag='life-profile',
        summary='Api Life Profile Delete',
    ),
    'delete_api_logs': Operation(
        operation_id='delete_api_logs',
        method='DELETE',
        path='/api/logs',
        auth='session',
        tag='logs',
        summary='Api Logs Clear',
    ),
    'delete_api_places_by_place_id': Operation(
        operation_id='delete_api_places_by_place_id',
        method='DELETE',
        path='/api/places/{place_id}',
        auth='session',
        tag='places',
        summary='Api Places Delete',
    ),
    'delete_api_tasks': Operation(
        operation_id='delete_api_tasks',
        method='DELETE',
        path='/api/tasks',
        auth='session',
        tag='tasks',
        summary='Api Tasks Delete All',
    ),
    'delete_api_tasks_by_task_id': Operation(
        operation_id='delete_api_tasks_by_task_id',
        method='DELETE',
        path='/api/tasks/{task_id}',
        auth='session',
        tag='tasks',
        summary='Api Tasks Delete',
    ),
    'get_api_agentic_runs': Operation(
        operation_id='get_api_agentic_runs',
        method='GET',
        path='/api/agentic/runs',
        auth='session_or_mobile',
        tag='agentic',
        summary='List Agentic Runs',
    ),
    'get_api_agentic_runs_by_run_id': Operation(
        operation_id='get_api_agentic_runs_by_run_id',
        method='GET',
        path='/api/agentic/runs/{run_id}',
        auth='session_or_mobile',
        tag='agentic',
        summary='Get Agentic Run',
    ),
    'get_api_agentic_runs_by_run_id_approvals': Operation(
        operation_id='get_api_agentic_runs_by_run_id_approvals',
        method='GET',
        path='/api/agentic/runs/{run_id}/approvals',
        auth='session_or_mobile',
        tag='agentic',
        summary='Get Agentic Run Approvals',
    ),
    'get_api_agentic_runs_by_run_id_artifacts': Operation(
        operation_id='get_api_agentic_runs_by_run_id_artifacts',
        method='GET',
        path='/api/agentic/runs/{run_id}/artifacts',
        auth='session_or_mobile',
        tag='agentic',
        summary='Get Agentic Run Artifacts',
    ),
    'get_api_agentic_runs_by_run_id_events': Operation(
        operation_id='get_api_agentic_runs_by_run_id_events',
        method='GET',
        path='/api/agentic/runs/{run_id}/events',
        auth='session_or_mobile',
        tag='agentic',
        summary='Get Agentic Run Events',
    ),
    'get_api_agentic_runtime_status': Operation(
        operation_id='get_api_agentic_runtime_status',
        method='GET',
        path='/api/agentic/runtime/status',
        auth='session_or_mobile',
        tag='agentic',
        summary='Agentic Runtime Status',
    ),
    'get_api_app_usage': Operation(
        operation_id='get_api_app_usage',
        method='GET',
        path='/api/app-usage',
        auth='session',
        tag='app-usage',
        summary='Api App Usage',
    ),
    'get_api_audio_daemon_status': Operation(
        operation_id='get_api_audio_daemon_status',
        method='GET',
        path='/api/audio-daemon/status',
        auth='session',
        tag='audio-daemon',
        summary='Audio Daemon Status',
    ),
    'get_api_auth_profiles': Operation(
        operation_id='get_api_auth_profiles',
        method='GET',
        path='/api/auth/profiles',
        auth='public',
        tag='authentication',
        summary='Api Auth Profiles',
    ),
    'get_api_auth_sessions': Operation(
        operation_id='get_api_auth_sessions',
        method='GET',
        path='/api/auth/sessions',
        auth='session',
        tag='authentication',
        summary='Api Auth Sessions',
    ),
    'get_api_auth_status': Operation(
        operation_id='get_api_auth_status',
        method='GET',
        path='/api/auth/status',
        auth='public',
        tag='authentication',
        summary='Api Auth Status',
    ),
    'get_api_autonomy_settings': Operation(
        operation_id='get_api_autonomy_settings',
        method='GET',
        path='/api/autonomy/settings',
        auth='session',
        tag='cognitive',
        summary='Autonomy Settings',
    ),
    'get_api_backups': Operation(
        operation_id='get_api_backups',
        method='GET',
        path='/api/backups',
        auth='session',
        tag='backups',
        summary='Api Backups List',
    ),
    'get_api_backups_cloud': Operation(
        operation_id='get_api_backups_cloud',
        method='GET',
        path='/api/backups/cloud',
        auth='session',
        tag='backups',
        summary='Api Cloud Backups List',
    ),
    'get_api_briefing': Operation(
        operation_id='get_api_briefing',
        method='GET',
        path='/api/briefing',
        auth='session_or_mobile',
        tag='briefing',
        summary='Api Briefing',
    ),
    'get_api_calendar': Operation(
        operation_id='get_api_calendar',
        method='GET',
        path='/api/calendar',
        auth='session_or_mobile',
        tag='calendar',
        summary='Api Calendar Get',
    ),
    'get_api_cognitive_capabilities': Operation(
        operation_id='get_api_cognitive_capabilities',
        method='GET',
        path='/api/cognitive/capabilities',
        auth='session',
        tag='cognitive',
        summary='Cognitive Capabilities',
    ),
    'get_api_cognitive_llm_policy': Operation(
        operation_id='get_api_cognitive_llm_policy',
        method='GET',
        path='/api/cognitive/llm-policy',
        auth='session',
        tag='cognitive',
        summary='Llm Policy',
    ),
    'get_api_commitments': Operation(
        operation_id='get_api_commitments',
        method='GET',
        path='/api/commitments',
        auth='session',
        tag='commitments',
        summary='Api Commitments List',
    ),
    'get_api_commitments_consistency': Operation(
        operation_id='get_api_commitments_consistency',
        method='GET',
        path='/api/commitments/consistency',
        auth='session',
        tag='commitments',
        summary='Api Commitments Consistency',
    ),
    'get_api_contacts': Operation(
        operation_id='get_api_contacts',
        method='GET',
        path='/api/contacts',
        auth='session',
        tag='contacts',
        summary='Api Mac Contacts',
    ),
    'get_api_contacts_resolve': Operation(
        operation_id='get_api_contacts_resolve',
        method='GET',
        path='/api/contacts/resolve',
        auth='session',
        tag='cognitive',
        summary='Contacts Resolve',
    ),
    'get_api_control_by_service_detail': Operation(
        operation_id='get_api_control_by_service_detail',
        method='GET',
        path='/api/control/{service}/detail',
        auth='session',
        tag='control',
        summary='Control Service Detail',
    ),
    'get_api_control_by_service_logs': Operation(
        operation_id='get_api_control_by_service_logs',
        method='GET',
        path='/api/control/{service}/logs',
        auth='session',
        tag='control',
        summary='Control Service Logs',
    ),
    'get_api_control_services': Operation(
        operation_id='get_api_control_services',
        method='GET',
        path='/api/control/services',
        auth='session',
        tag='control',
        summary='Control List Services',
    ),
    'get_api_conversations': Operation(
        operation_id='get_api_conversations',
        method='GET',
        path='/api/conversations',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversations List',
    ),
    'get_api_conversations_by_conv_id': Operation(
        operation_id='get_api_conversations_by_conv_id',
        method='GET',
        path='/api/conversations/{conv_id}',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversation Get',
    ),
    'get_api_conversations_search': Operation(
        operation_id='get_api_conversations_search',
        method='GET',
        path='/api/conversations/search',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversations Search',
    ),
    'get_api_costs': Operation(
        operation_id='get_api_costs',
        method='GET',
        path='/api/costs',
        auth='session',
        tag='costs',
        summary='Api Costs',
    ),
    'get_api_cursor_jobs': Operation(
        operation_id='get_api_cursor_jobs',
        method='GET',
        path='/api/cursor/jobs',
        auth='session',
        tag='cognitive',
        summary='Cursor Jobs',
    ),
    'get_api_cursor_jobs_by_job_id': Operation(
        operation_id='get_api_cursor_jobs_by_job_id',
        method='GET',
        path='/api/cursor/jobs/{job_id}',
        auth='session',
        tag='cognitive',
        summary='Cursor Job Detail',
    ),
    'get_api_cursor_status': Operation(
        operation_id='get_api_cursor_status',
        method='GET',
        path='/api/cursor/status',
        auth='session',
        tag='cognitive',
        summary='Cursor Status',
    ),
    'get_api_day_scores': Operation(
        operation_id='get_api_day_scores',
        method='GET',
        path='/api/day-scores',
        auth='session',
        tag='day-scores',
        summary='Api Day Scores',
    ),
    'get_api_day_scores_by_date': Operation(
        operation_id='get_api_day_scores_by_date',
        method='GET',
        path='/api/day-scores/{date}',
        auth='session',
        tag='day-scores',
        summary='Api Day Score Detail',
    ),
    'get_api_devagent_by_project_id_deployments': Operation(
        operation_id='get_api_devagent_by_project_id_deployments',
        method='GET',
        path='/api/devagent/{project_id}/deployments',
        auth='session',
        tag='devagent',
        summary='Api Devagent Deployments',
    ),
    'get_api_devagent_by_project_id_status': Operation(
        operation_id='get_api_devagent_by_project_id_status',
        method='GET',
        path='/api/devagent/{project_id}/status',
        auth='session',
        tag='devagent',
        summary='Devagent Status',
    ),
    'get_api_developer_docs': Operation(
        operation_id='get_api_developer_docs',
        method='GET',
        path='/api/developer/docs',
        auth='session',
        tag='developer',
        summary='Api Developer Docs',
    ),
    'get_api_developer_openapi_json': Operation(
        operation_id='get_api_developer_openapi_json',
        method='GET',
        path='/api/developer/openapi.json',
        auth='session',
        tag='developer',
        summary='Api Developer Openapi',
    ),
    'get_api_devices': Operation(
        operation_id='get_api_devices',
        method='GET',
        path='/api/devices',
        auth='session',
        tag='devices',
        summary='Api List Devices',
    ),
    'get_api_devices_by_device_id_tts': Operation(
        operation_id='get_api_devices_by_device_id_tts',
        method='GET',
        path='/api/devices/{device_id}/tts',
        auth='device_token',
        tag='devices',
        summary='Api Device Tts',
    ),
    'get_api_dnd': Operation(
        operation_id='get_api_dnd',
        method='GET',
        path='/api/dnd',
        auth='session',
        tag='dnd',
        summary='Api Dnd Status',
    ),
    'get_api_doomscroll': Operation(
        operation_id='get_api_doomscroll',
        method='GET',
        path='/api/doomscroll',
        auth='session',
        tag='doomscroll',
        summary='Api Doomscroll',
    ),
    'get_api_emails': Operation(
        operation_id='get_api_emails',
        method='GET',
        path='/api/emails',
        auth='session',
        tag='emails',
        summary='Api Emails',
    ),
    'get_api_events_stream': Operation(
        operation_id='get_api_events_stream',
        method='GET',
        path='/api/events/stream',
        auth='session',
        tag='events',
        summary='Events Stream',
    ),
    'get_api_export': Operation(
        operation_id='get_api_export',
        method='GET',
        path='/api/export',
        auth='session',
        tag='export',
        summary='Api Export Dump',
    ),
    'get_api_fitness_dashboard': Operation(
        operation_id='get_api_fitness_dashboard',
        method='GET',
        path='/api/fitness/dashboard',
        auth='session',
        tag='fitness',
        summary='Get Dashboard',
    ),
    'get_api_fitness_meals': Operation(
        operation_id='get_api_fitness_meals',
        method='GET',
        path='/api/fitness/meals',
        auth='session',
        tag='fitness',
        summary='Get Meals',
    ),
    'get_api_fitness_meals_by_meal_id_photo': Operation(
        operation_id='get_api_fitness_meals_by_meal_id_photo',
        method='GET',
        path='/api/fitness/meals/{meal_id}/photo',
        auth='session',
        tag='fitness',
        summary='Get Meal Photo',
    ),
    'get_api_fitness_program': Operation(
        operation_id='get_api_fitness_program',
        method='GET',
        path='/api/fitness/program',
        auth='session',
        tag='fitness',
        summary='Get Program',
    ),
    'get_api_fitness_summary_today': Operation(
        operation_id='get_api_fitness_summary_today',
        method='GET',
        path='/api/fitness/summary/today',
        auth='session',
        tag='fitness',
        summary='Get Today Summary',
    ),
    'get_api_fitness_water_today': Operation(
        operation_id='get_api_fitness_water_today',
        method='GET',
        path='/api/fitness/water/today',
        auth='session',
        tag='fitness',
        summary='Get Water Today',
    ),
    'get_api_fitness_weights': Operation(
        operation_id='get_api_fitness_weights',
        method='GET',
        path='/api/fitness/weights',
        auth='session',
        tag='fitness',
        summary='Get Weights',
    ),
    'get_api_fitness_wellbeing': Operation(
        operation_id='get_api_fitness_wellbeing',
        method='GET',
        path='/api/fitness/wellbeing',
        auth='session',
        tag='fitness',
        summary='Get Wellbeing',
    ),
    'get_api_fitness_workouts': Operation(
        operation_id='get_api_fitness_workouts',
        method='GET',
        path='/api/fitness/workouts',
        auth='session',
        tag='fitness',
        summary='Get Workouts',
    ),
    'get_api_food_cart_by_plan_id': Operation(
        operation_id='get_api_food_cart_by_plan_id',
        method='GET',
        path='/api/food/cart/{plan_id}',
        auth='session',
        tag='food',
        summary='Api Food Cart Peek',
    ),
    'get_api_food_delivery': Operation(
        operation_id='get_api_food_delivery',
        method='GET',
        path='/api/food/delivery',
        auth='session',
        tag='food',
        summary='Api Food Delivery',
    ),
    'get_api_food_menus': Operation(
        operation_id='get_api_food_menus',
        method='GET',
        path='/api/food/menus',
        auth='session',
        tag='food',
        summary='Api Food Menus',
    ),
    'get_api_food_menus_by_restaurant': Operation(
        operation_id='get_api_food_menus_by_restaurant',
        method='GET',
        path='/api/food/menus/{restaurant}',
        auth='session',
        tag='food',
        summary='Api Food Menu Items',
    ),
    'get_api_food_orders': Operation(
        operation_id='get_api_food_orders',
        method='GET',
        path='/api/food/orders',
        auth='session',
        tag='food',
        summary='Api Food Orders',
    ),
    'get_api_food_preferences': Operation(
        operation_id='get_api_food_preferences',
        method='GET',
        path='/api/food/preferences',
        auth='session',
        tag='food',
        summary='Api Food Preferences',
    ),
    'get_api_food_selectors': Operation(
        operation_id='get_api_food_selectors',
        method='GET',
        path='/api/food/selectors',
        auth='session',
        tag='food',
        summary='Api Food Selectors',
    ),
    'get_api_food_session': Operation(
        operation_id='get_api_food_session',
        method='GET',
        path='/api/food/session',
        auth='session',
        tag='food',
        summary='Api Food Session',
    ),
    'get_api_food_session_capture': Operation(
        operation_id='get_api_food_session_capture',
        method='GET',
        path='/api/food/session/capture',
        auth='session',
        tag='food',
        summary='Api Food Session Capture Status',
    ),
    'get_api_food_settings': Operation(
        operation_id='get_api_food_settings',
        method='GET',
        path='/api/food/settings',
        auth='session',
        tag='food',
        summary='Api Food Settings',
    ),
    'get_api_food_status': Operation(
        operation_id='get_api_food_status',
        method='GET',
        path='/api/food/status',
        auth='session',
        tag='food',
        summary='Api Food Status',
    ),
    'get_api_food_suggestions': Operation(
        operation_id='get_api_food_suggestions',
        method='GET',
        path='/api/food/suggestions',
        auth='session',
        tag='food',
        summary='Api Food Suggestions',
    ),
    'get_api_health_detail': Operation(
        operation_id='get_api_health_detail',
        method='GET',
        path='/api/health/detail',
        auth='session',
        tag='health',
        summary='Api Health Detail',
    ),
    'get_api_health_live': Operation(
        operation_id='get_api_health_live',
        method='GET',
        path='/api/health/live',
        auth='public',
        tag='health',
        summary='Api Health Live',
    ),
    'get_api_imessage_import_status': Operation(
        operation_id='get_api_imessage_import_status',
        method='GET',
        path='/api/imessage-import/status',
        auth='session',
        tag='imessage-import',
        summary='Api Imessage Import Status',
    ),
    'get_api_improvements_proposals': Operation(
        operation_id='get_api_improvements_proposals',
        method='GET',
        path='/api/improvements/proposals',
        auth='session',
        tag='cognitive',
        summary='Improvement Proposals',
    ),
    'get_api_integrations': Operation(
        operation_id='get_api_integrations',
        method='GET',
        path='/api/integrations',
        auth='session',
        tag='integrations',
        summary='Api Integrations',
    ),
    'get_api_jarvis_journal': Operation(
        operation_id='get_api_jarvis_journal',
        method='GET',
        path='/api/jarvis-journal',
        auth='session',
        tag='jarvis-journal',
        summary='Api Jarvis Journal',
    ),
    'get_api_journal': Operation(
        operation_id='get_api_journal',
        method='GET',
        path='/api/journal',
        auth='session',
        tag='journal',
        summary='Api Journal Get',
    ),
    'get_api_life_context': Operation(
        operation_id='get_api_life_context',
        method='GET',
        path='/api/life-context',
        auth='session',
        tag='life-context',
        summary='Api Life Context List',
    ),
    'get_api_life_profile': Operation(
        operation_id='get_api_life_profile',
        method='GET',
        path='/api/life-profile',
        auth='session',
        tag='life-profile',
        summary='Api Life Profile Get',
    ),
    'get_api_location_history': Operation(
        operation_id='get_api_location_history',
        method='GET',
        path='/api/location/history',
        auth='session',
        tag='location',
        summary='Api Location History',
    ),
    'get_api_location_patterns': Operation(
        operation_id='get_api_location_patterns',
        method='GET',
        path='/api/location/patterns',
        auth='session',
        tag='location',
        summary='Api Location Patterns',
    ),
    'get_api_location_status': Operation(
        operation_id='get_api_location_status',
        method='GET',
        path='/api/location/status',
        auth='session_or_mobile',
        tag='location',
        summary='Api Location Status',
    ),
    'get_api_logs': Operation(
        operation_id='get_api_logs',
        method='GET',
        path='/api/logs',
        auth='session',
        tag='logs',
        summary='Api Logs',
    ),
    'get_api_meetings': Operation(
        operation_id='get_api_meetings',
        method='GET',
        path='/api/meetings',
        auth='session',
        tag='meetings',
        summary='Api Meetings List',
    ),
    'get_api_memory': Operation(
        operation_id='get_api_memory',
        method='GET',
        path='/api/memory',
        auth='session',
        tag='memory',
        summary='Api Memory Get',
    ),
    'get_api_memory_search_semantic': Operation(
        operation_id='get_api_memory_search_semantic',
        method='GET',
        path='/api/memory/search-semantic',
        auth='session',
        tag='memory',
        summary='Api Memory Search Semantic',
    ),
    'get_api_metrics_history': Operation(
        operation_id='get_api_metrics_history',
        method='GET',
        path='/api/metrics/history',
        auth='session',
        tag='observability',
        summary='Api Metrics History',
    ),
    'get_api_migrations_status': Operation(
        operation_id='get_api_migrations_status',
        method='GET',
        path='/api/migrations/status',
        auth='session',
        tag='migrations',
        summary='Api Migrations Status',
    ),
    'get_api_mobile_devices': Operation(
        operation_id='get_api_mobile_devices',
        method='GET',
        path='/api/mobile/devices',
        auth='session',
        tag='mobile',
        summary='Api Mobile Devices',
    ),
    'get_api_mobile_location_diagnostics': Operation(
        operation_id='get_api_mobile_location_diagnostics',
        method='GET',
        path='/api/mobile/location/diagnostics',
        auth='session_or_mobile',
        tag='mobile',
        summary='Api Mobile Location Diagnostics',
    ),
    'get_api_mood': Operation(
        operation_id='get_api_mood',
        method='GET',
        path='/api/mood',
        auth='session',
        tag='mood',
        summary='Api Mood',
    ),
    'get_api_mood_signals': Operation(
        operation_id='get_api_mood_signals',
        method='GET',
        path='/api/mood/signals',
        auth='session',
        tag='mood',
        summary='Api Mood Signals',
    ),
    'get_api_notifications': Operation(
        operation_id='get_api_notifications',
        method='GET',
        path='/api/notifications',
        auth='session_or_mobile',
        tag='notifications',
        summary='Api Notifications Unread',
    ),
    'get_api_notifications_all': Operation(
        operation_id='get_api_notifications_all',
        method='GET',
        path='/api/notifications/all',
        auth='session_or_mobile',
        tag='notifications',
        summary='Api Notifications All',
    ),
    'get_api_outputs': Operation(
        operation_id='get_api_outputs',
        method='GET',
        path='/api/outputs',
        auth='session',
        tag='outputs',
        summary='Api Outputs List',
    ),
    'get_api_outputs_by_filepath': Operation(
        operation_id='get_api_outputs_by_filepath',
        method='GET',
        path='/api/outputs/{filepath}',
        auth='session',
        tag='outputs',
        summary='Api Outputs Download',
    ),
    'get_api_patterns': Operation(
        operation_id='get_api_patterns',
        method='GET',
        path='/api/patterns',
        auth='session',
        tag='patterns',
        summary='Api Patterns Get',
    ),
    'get_api_people': Operation(
        operation_id='get_api_people',
        method='GET',
        path='/api/people',
        auth='session',
        tag='people',
        summary='Api People List',
    ),
    'get_api_people_by_name': Operation(
        operation_id='get_api_people_by_name',
        method='GET',
        path='/api/people/{name}',
        auth='session',
        tag='people',
        summary='Api People Detail',
    ),
    'get_api_people_by_name_analytics': Operation(
        operation_id='get_api_people_by_name_analytics',
        method='GET',
        path='/api/people/{name}/analytics',
        auth='session',
        tag='people',
        summary='Api Person Analytics',
    ),
    'get_api_people_by_name_description': Operation(
        operation_id='get_api_people_by_name_description',
        method='GET',
        path='/api/people/{name}/description',
        auth='session',
        tag='people',
        summary='Api Person Description',
    ),
    'get_api_people_by_name_timeline': Operation(
        operation_id='get_api_people_by_name_timeline',
        method='GET',
        path='/api/people/{name}/timeline',
        auth='session',
        tag='people',
        summary='Api Person Timeline Haiku',
    ),
    'get_api_places': Operation(
        operation_id='get_api_places',
        method='GET',
        path='/api/places',
        auth='session',
        tag='places',
        summary='Api Places List',
    ),
    'get_api_places_by_place_id_stats': Operation(
        operation_id='get_api_places_by_place_id_stats',
        method='GET',
        path='/api/places/{place_id}/stats',
        auth='session',
        tag='places',
        summary='Api Place Stats',
    ),
    'get_api_places_favorites': Operation(
        operation_id='get_api_places_favorites',
        method='GET',
        path='/api/places/favorites',
        auth='session',
        tag='places',
        summary='Api Places Favorites',
    ),
    'get_api_places_missed_opportunities': Operation(
        operation_id='get_api_places_missed_opportunities',
        method='GET',
        path='/api/places/missed-opportunities',
        auth='session',
        tag='places',
        summary='Api Places Missed Opportunities',
    ),
    'get_api_predictions_messages': Operation(
        operation_id='get_api_predictions_messages',
        method='GET',
        path='/api/predictions/messages',
        auth='session',
        tag='predictions',
        summary='Api Predictions Messages',
    ),
    'get_api_presence': Operation(
        operation_id='get_api_presence',
        method='GET',
        path='/api/presence',
        auth='session',
        tag='presence',
        summary='Api Presence',
    ),
    'get_api_privacy_documents': Operation(
        operation_id='get_api_privacy_documents',
        method='GET',
        path='/api/privacy/documents',
        auth='session',
        tag='privacy',
        summary='Api Document Privacy Get',
    ),
    'get_api_procrastination_cost': Operation(
        operation_id='get_api_procrastination_cost',
        method='GET',
        path='/api/procrastination/cost',
        auth='session',
        tag='procrastination',
        summary='Api Procrastination Cost',
    ),
    'get_api_productivity_score': Operation(
        operation_id='get_api_productivity_score',
        method='GET',
        path='/api/productivity/score',
        auth='session',
        tag='productivity',
        summary='Api Productivity Score',
    ),
    'get_api_push_vapid_public_key': Operation(
        operation_id='get_api_push_vapid_public_key',
        method='GET',
        path='/api/push/vapid-public-key',
        auth='session',
        tag='push',
        summary='Api Push Vapid Public Key',
    ),
    'get_api_quality_duplicates': Operation(
        operation_id='get_api_quality_duplicates',
        method='GET',
        path='/api/quality/duplicates',
        auth='session',
        tag='quality',
        summary='Api Quality Duplicates',
    ),
    'get_api_quality_security': Operation(
        operation_id='get_api_quality_security',
        method='GET',
        path='/api/quality/security',
        auth='session',
        tag='quality',
        summary='Api Quality Security',
    ),
    'get_api_recordings': Operation(
        operation_id='get_api_recordings',
        method='GET',
        path='/api/recordings',
        auth='session',
        tag='recordings',
        summary='Api Recordings List',
    ),
    'get_api_recordings_by_recording_id': Operation(
        operation_id='get_api_recordings_by_recording_id',
        method='GET',
        path='/api/recordings/{recording_id}',
        auth='session',
        tag='recordings',
        summary='Api Recordings Detail',
    ),
    'get_api_recordings_by_recording_id_speakers': Operation(
        operation_id='get_api_recordings_by_recording_id_speakers',
        method='GET',
        path='/api/recordings/{recording_id}/speakers',
        auth='session',
        tag='recordings',
        summary='Api Recording Unlabeled Speakers',
    ),
    'get_api_recordings_by_recording_id_turns': Operation(
        operation_id='get_api_recordings_by_recording_id_turns',
        method='GET',
        path='/api/recordings/{recording_id}/turns',
        auth='session',
        tag='recordings',
        summary='Api Recording Turns',
    ),
    'get_api_relationship_by_name': Operation(
        operation_id='get_api_relationship_by_name',
        method='GET',
        path='/api/relationship/{name}',
        auth='session',
        tag='relationship',
        summary='Api Relationship Detail',
    ),
    'get_api_relationship_graph': Operation(
        operation_id='get_api_relationship_graph',
        method='GET',
        path='/api/relationship-graph',
        auth='session',
        tag='relationship-graph',
        summary='Api Relationship Graph',
    ),
    'get_api_rituals_today': Operation(
        operation_id='get_api_rituals_today',
        method='GET',
        path='/api/rituals/today',
        auth='session',
        tag='rituals',
        summary='Api Rituals Today',
    ),
    'get_api_scheduler_jobs': Operation(
        operation_id='get_api_scheduler_jobs',
        method='GET',
        path='/api/scheduler/jobs',
        auth='session',
        tag='scheduler',
        summary='Api Scheduler Jobs',
    ),
    'get_api_scheduler_jobs_by_job_id_runs': Operation(
        operation_id='get_api_scheduler_jobs_by_job_id_runs',
        method='GET',
        path='/api/scheduler/jobs/{job_id}/runs',
        auth='session',
        tag='scheduler',
        summary='Api Scheduler Job Runs',
    ),
    'get_api_screen_activity': Operation(
        operation_id='get_api_screen_activity',
        method='GET',
        path='/api/screen-activity',
        auth='session',
        tag='screen-activity',
        summary='Api Screen Activity',
    ),
    'get_api_screen_activity_current': Operation(
        operation_id='get_api_screen_activity_current',
        method='GET',
        path='/api/screen-activity/current',
        auth='session',
        tag='screen-activity',
        summary='Api Screen Activity Current',
    ),
    'get_api_search': Operation(
        operation_id='get_api_search',
        method='GET',
        path='/api/search',
        auth='session',
        tag='search',
        summary='Api Search',
    ),
    'get_api_self_healing_status': Operation(
        operation_id='get_api_self_healing_status',
        method='GET',
        path='/api/self-healing/status',
        auth='session',
        tag='self-healing',
        summary='Api Self Healing Status',
    ),
    'get_api_settings_tts': Operation(
        operation_id='get_api_settings_tts',
        method='GET',
        path='/api/settings/tts',
        auth='session',
        tag='settings',
        summary='Api Get Tts Setting',
    ),
    'get_api_stats_compare': Operation(
        operation_id='get_api_stats_compare',
        method='GET',
        path='/api/stats/compare',
        auth='session',
        tag='observability',
        summary='Api Stats Compare',
    ),
    'get_api_stats_weekly': Operation(
        operation_id='get_api_stats_weekly',
        method='GET',
        path='/api/stats/weekly',
        auth='session',
        tag='observability',
        summary='Api Stats Weekly',
    ),
    'get_api_status': Operation(
        operation_id='get_api_status',
        method='GET',
        path='/api/status',
        auth='session',
        tag='status',
        summary='Api Status',
    ),
    'get_api_task_candidates': Operation(
        operation_id='get_api_task_candidates',
        method='GET',
        path='/api/task-candidates',
        auth='session',
        tag='task-control',
        summary='List Task Candidates',
    ),
    'get_api_task_control_tasks': Operation(
        operation_id='get_api_task_control_tasks',
        method='GET',
        path='/api/task-control/tasks',
        auth='session',
        tag='task-control',
        summary='List Control Tasks',
    ),
    'get_api_task_control_tasks_by_task_id': Operation(
        operation_id='get_api_task_control_tasks_by_task_id',
        method='GET',
        path='/api/task-control/tasks/{task_id}',
        auth='session',
        tag='task-control',
        summary='Get Control Task',
    ),
    'get_api_task_control_tasks_by_task_id_activity': Operation(
        operation_id='get_api_task_control_tasks_by_task_id_activity',
        method='GET',
        path='/api/task-control/tasks/{task_id}/activity',
        auth='session',
        tag='task-control',
        summary='Get Control Activity',
    ),
    'get_api_task_control_tasks_by_task_id_approvals': Operation(
        operation_id='get_api_task_control_tasks_by_task_id_approvals',
        method='GET',
        path='/api/task-control/tasks/{task_id}/approvals',
        auth='session',
        tag='task-control',
        summary='List Control Approvals',
    ),
    'get_api_task_control_tasks_by_task_id_artifacts': Operation(
        operation_id='get_api_task_control_tasks_by_task_id_artifacts',
        method='GET',
        path='/api/task-control/tasks/{task_id}/artifacts',
        auth='session',
        tag='task-control',
        summary='Get Control Artifacts',
    ),
    'get_api_task_control_tasks_by_task_id_plans': Operation(
        operation_id='get_api_task_control_tasks_by_task_id_plans',
        method='GET',
        path='/api/task-control/tasks/{task_id}/plans',
        auth='session',
        tag='task-control',
        summary='List Control Plans',
    ),
    'get_api_task_control_tasks_by_task_id_report': Operation(
        operation_id='get_api_task_control_tasks_by_task_id_report',
        method='GET',
        path='/api/task-control/tasks/{task_id}/report',
        auth='session',
        tag='task-control',
        summary='Get Control Report',
    ),
    'get_api_tasks': Operation(
        operation_id='get_api_tasks',
        method='GET',
        path='/api/tasks',
        auth='session_or_mobile',
        tag='tasks',
        summary='Api Tasks List',
    ),
    'get_api_time_machine_by_date': Operation(
        operation_id='get_api_time_machine_by_date',
        method='GET',
        path='/api/time-machine/{date}',
        auth='session',
        tag='time-machine',
        summary='Api Time Machine',
    ),
    'get_api_trips': Operation(
        operation_id='get_api_trips',
        method='GET',
        path='/api/trips',
        auth='session',
        tag='trips',
        summary='Api Trips List',
    ),
    'get_api_visits': Operation(
        operation_id='get_api_visits',
        method='GET',
        path='/api/visits',
        auth='session',
        tag='visits',
        summary='Api Visits List',
    ),
    'get_api_visits_today': Operation(
        operation_id='get_api_visits_today',
        method='GET',
        path='/api/visits/today',
        auth='session_or_mobile',
        tag='visits',
        summary='Api Visits Today',
    ),
    'get_api_voice_debug': Operation(
        operation_id='get_api_voice_debug',
        method='GET',
        path='/api/voice-debug',
        auth='session',
        tag='voice-debug',
        summary='Api Voice Debug Logs',
    ),
    'get_api_voice_metrics': Operation(
        operation_id='get_api_voice_metrics',
        method='GET',
        path='/api/voice/metrics',
        auth='session',
        tag='cognitive',
        summary='Voice Metrics',
    ),
    'patch_api_commitments_by_commitment_id': Operation(
        operation_id='patch_api_commitments_by_commitment_id',
        method='PATCH',
        path='/api/commitments/{commitment_id}',
        auth='session',
        tag='commitments',
        summary='Api Commitments Update',
    ),
    'patch_api_conversations_by_conv_id': Operation(
        operation_id='patch_api_conversations_by_conv_id',
        method='PATCH',
        path='/api/conversations/{conv_id}',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversation Update',
    ),
    'patch_api_fitness_program': Operation(
        operation_id='patch_api_fitness_program',
        method='PATCH',
        path='/api/fitness/program',
        auth='session',
        tag='fitness',
        summary='Update Program',
    ),
    'patch_api_fitness_program_sessions_by_session_id': Operation(
        operation_id='patch_api_fitness_program_sessions_by_session_id',
        method='PATCH',
        path='/api/fitness/program/sessions/{session_id}',
        auth='session',
        tag='fitness',
        summary='Update Program Session',
    ),
    'patch_api_food_settings': Operation(
        operation_id='patch_api_food_settings',
        method='PATCH',
        path='/api/food/settings',
        auth='session',
        tag='food',
        summary='Api Food Settings Update',
    ),
    'patch_api_people_by_name': Operation(
        operation_id='patch_api_people_by_name',
        method='PATCH',
        path='/api/people/{name}',
        auth='session',
        tag='people',
        summary='Api People Patch',
    ),
    'patch_api_settings_tts': Operation(
        operation_id='patch_api_settings_tts',
        method='PATCH',
        path='/api/settings/tts',
        auth='session',
        tag='settings',
        summary='Api Set Tts Setting',
    ),
    'patch_api_task_control_tasks_by_task_id': Operation(
        operation_id='patch_api_task_control_tasks_by_task_id',
        method='PATCH',
        path='/api/task-control/tasks/{task_id}',
        auth='session',
        tag='task-control',
        summary='Patch Control Task',
    ),
    'patch_api_tasks_by_task_id': Operation(
        operation_id='patch_api_tasks_by_task_id',
        method='PATCH',
        path='/api/tasks/{task_id}',
        auth='session',
        tag='tasks',
        summary='Api Tasks Update',
    ),
    'post_api_agentic_runs': Operation(
        operation_id='post_api_agentic_runs',
        method='POST',
        path='/api/agentic/runs',
        auth='session_or_mobile',
        tag='agentic',
        summary='Create Agentic Run',
    ),
    'post_api_agentic_runs_by_run_id_approvals_by_approval_id_decision': Operation(
        operation_id='post_api_agentic_runs_by_run_id_approvals_by_approval_id_decision',
        method='POST',
        path='/api/agentic/runs/{run_id}/approvals/{approval_id}/decision',
        auth='session_or_mobile',
        tag='agentic',
        summary='Decide Agentic Approval',
    ),
    'post_api_agentic_runs_by_run_id_cancel': Operation(
        operation_id='post_api_agentic_runs_by_run_id_cancel',
        method='POST',
        path='/api/agentic/runs/{run_id}/cancel',
        auth='session_or_mobile',
        tag='agentic',
        summary='Cancel Agentic Run',
    ),
    'post_api_agentic_runs_by_run_id_pause': Operation(
        operation_id='post_api_agentic_runs_by_run_id_pause',
        method='POST',
        path='/api/agentic/runs/{run_id}/pause',
        auth='session_or_mobile',
        tag='agentic',
        summary='Pause Agentic Run',
    ),
    'post_api_agentic_runs_by_run_id_resume': Operation(
        operation_id='post_api_agentic_runs_by_run_id_resume',
        method='POST',
        path='/api/agentic/runs/{run_id}/resume',
        auth='session_or_mobile',
        tag='agentic',
        summary='Resume Agentic Run',
    ),
    'post_api_analyze_contact': Operation(
        operation_id='post_api_analyze_contact',
        method='POST',
        path='/api/analyze-contact',
        auth='session',
        tag='analyze-contact',
        summary='Api Analyze Contact',
    ),
    'post_api_audio_daemon_continuous': Operation(
        operation_id='post_api_audio_daemon_continuous',
        method='POST',
        path='/api/audio-daemon/continuous',
        auth='session',
        tag='audio-daemon',
        summary='Audio Daemon Continuous',
    ),
    'post_api_audio_daemon_start': Operation(
        operation_id='post_api_audio_daemon_start',
        method='POST',
        path='/api/audio-daemon/start',
        auth='session',
        tag='audio-daemon',
        summary='Audio Daemon Start',
    ),
    'post_api_audio_daemon_stop': Operation(
        operation_id='post_api_audio_daemon_stop',
        method='POST',
        path='/api/audio-daemon/stop',
        auth='session',
        tag='audio-daemon',
        summary='Audio Daemon Stop',
    ),
    'post_api_audio_daemon_wake_word': Operation(
        operation_id='post_api_audio_daemon_wake_word',
        method='POST',
        path='/api/audio-daemon/wake-word',
        auth='session',
        tag='audio-daemon',
        summary='Audio Daemon Wake Word',
    ),
    'post_api_auth_change_secret': Operation(
        operation_id='post_api_auth_change_secret',
        method='POST',
        path='/api/auth/change-secret',
        auth='session',
        tag='authentication',
        summary='Api Auth Change Secret',
    ),
    'post_api_auth_local_unlock': Operation(
        operation_id='post_api_auth_local_unlock',
        method='POST',
        path='/api/auth/local-unlock',
        auth='public',
        tag='authentication',
        summary='Api Auth Local Unlock',
    ),
    'post_api_auth_logout': Operation(
        operation_id='post_api_auth_logout',
        method='POST',
        path='/api/auth/logout',
        auth='session',
        tag='authentication',
        summary='Api Auth Logout',
    ),
    'post_api_auth_profiles': Operation(
        operation_id='post_api_auth_profiles',
        method='POST',
        path='/api/auth/profiles',
        auth='session',
        tag='authentication',
        summary='Api Auth Profile Create',
    ),
    'post_api_auth_profiles_by_profile_id_deactivate': Operation(
        operation_id='post_api_auth_profiles_by_profile_id_deactivate',
        method='POST',
        path='/api/auth/profiles/{profile_id}/deactivate',
        auth='session',
        tag='authentication',
        summary='Api Auth Profile Deactivate',
    ),
    'post_api_auth_sessions_by_session_id_revoke': Operation(
        operation_id='post_api_auth_sessions_by_session_id_revoke',
        method='POST',
        path='/api/auth/sessions/{session_id}/revoke',
        auth='session',
        tag='authentication',
        summary='Api Auth Revoke Session',
    ),
    'post_api_auth_setup': Operation(
        operation_id='post_api_auth_setup',
        method='POST',
        path='/api/auth/setup',
        auth='public',
        tag='authentication',
        summary='Api Auth Setup',
    ),
    'post_api_auth_unlock': Operation(
        operation_id='post_api_auth_unlock',
        method='POST',
        path='/api/auth/unlock',
        auth='public',
        tag='authentication',
        summary='Api Auth Unlock',
    ),
    'post_api_auth_verify': Operation(
        operation_id='post_api_auth_verify',
        method='POST',
        path='/api/auth/verify',
        auth='public',
        tag='authentication',
        summary='Api Auth Verify',
    ),
    'post_api_backups_by_name_restore': Operation(
        operation_id='post_api_backups_by_name_restore',
        method='POST',
        path='/api/backups/{name}/restore',
        auth='session',
        tag='backups',
        summary='Api Backups Restore',
    ),
    'post_api_backups_cloud_by_name_restore': Operation(
        operation_id='post_api_backups_cloud_by_name_restore',
        method='POST',
        path='/api/backups/cloud/{name}/restore',
        auth='session',
        tag='backups',
        summary='Api Cloud Backup Restore',
    ),
    'post_api_backups_run': Operation(
        operation_id='post_api_backups_run',
        method='POST',
        path='/api/backups/run',
        auth='session',
        tag='backups',
        summary='Api Backups Run',
    ),
    'post_api_briefings_generate': Operation(
        operation_id='post_api_briefings_generate',
        method='POST',
        path='/api/briefings/generate',
        auth='session',
        tag='cognitive',
        summary='Briefing Generate',
    ),
    'post_api_calendar': Operation(
        operation_id='post_api_calendar',
        method='POST',
        path='/api/calendar',
        auth='session',
        tag='calendar',
        summary='Api Calendar Create',
    ),
    'post_api_calendar_test': Operation(
        operation_id='post_api_calendar_test',
        method='POST',
        path='/api/calendar/test',
        auth='session',
        tag='calendar',
        summary='Api Calendar Test',
    ),
    'post_api_cognitive_route': Operation(
        operation_id='post_api_cognitive_route',
        method='POST',
        path='/api/cognitive/route',
        auth='session',
        tag='cognitive',
        summary='Cognitive Route',
    ),
    'post_api_contacts_sync': Operation(
        operation_id='post_api_contacts_sync',
        method='POST',
        path='/api/contacts/sync',
        auth='session',
        tag='contacts',
        summary='Api Contacts Sync',
    ),
    'post_api_control_by_service_restart': Operation(
        operation_id='post_api_control_by_service_restart',
        method='POST',
        path='/api/control/{service}/restart',
        auth='session',
        tag='control',
        summary='Control Restart Service',
    ),
    'post_api_control_by_service_start': Operation(
        operation_id='post_api_control_by_service_start',
        method='POST',
        path='/api/control/{service}/start',
        auth='session',
        tag='control',
        summary='Control Start Service',
    ),
    'post_api_control_by_service_stop': Operation(
        operation_id='post_api_control_by_service_stop',
        method='POST',
        path='/api/control/{service}/stop',
        auth='session',
        tag='control',
        summary='Control Stop Service',
    ),
    'post_api_control_restart_all': Operation(
        operation_id='post_api_control_restart_all',
        method='POST',
        path='/api/control/restart-all',
        auth='session',
        tag='control',
        summary='Control Restart All',
    ),
    'post_api_control_start_all': Operation(
        operation_id='post_api_control_start_all',
        method='POST',
        path='/api/control/start-all',
        auth='session',
        tag='control',
        summary='Control Start All',
    ),
    'post_api_control_stop_all': Operation(
        operation_id='post_api_control_stop_all',
        method='POST',
        path='/api/control/stop-all',
        auth='session',
        tag='control',
        summary='Control Stop All',
    ),
    'post_api_conversations_by_conv_id_archive': Operation(
        operation_id='post_api_conversations_by_conv_id_archive',
        method='POST',
        path='/api/conversations/{conv_id}/archive',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversation Archive',
    ),
    'post_api_conversations_by_conv_id_pin': Operation(
        operation_id='post_api_conversations_by_conv_id_pin',
        method='POST',
        path='/api/conversations/{conv_id}/pin',
        auth='session_or_mobile',
        tag='conversations',
        summary='Api Conversation Pin',
    ),
    'post_api_conversations_by_conv_id_upload': Operation(
        operation_id='post_api_conversations_by_conv_id_upload',
        method='POST',
        path='/api/conversations/{conv_id}/upload',
        auth='session',
        tag='conversations',
        summary='Api Conversation Upload',
    ),
    'post_api_cursor_jobs': Operation(
        operation_id='post_api_cursor_jobs',
        method='POST',
        path='/api/cursor/jobs',
        auth='session',
        tag='cognitive',
        summary='Cursor Enqueue',
    ),
    'post_api_cursor_jobs_by_job_id_cancel': Operation(
        operation_id='post_api_cursor_jobs_by_job_id_cancel',
        method='POST',
        path='/api/cursor/jobs/{job_id}/cancel',
        auth='session',
        tag='cognitive',
        summary='Cursor Cancel',
    ),
    'post_api_cursor_jobs_by_job_id_confirm': Operation(
        operation_id='post_api_cursor_jobs_by_job_id_confirm',
        method='POST',
        path='/api/cursor/jobs/{job_id}/confirm',
        auth='session',
        tag='cognitive',
        summary='Cursor Confirm',
    ),
    'post_api_cursor_jobs_by_job_id_retry': Operation(
        operation_id='post_api_cursor_jobs_by_job_id_retry',
        method='POST',
        path='/api/cursor/jobs/{job_id}/retry',
        auth='session',
        tag='cognitive',
        summary='Cursor Retry',
    ),
    'post_api_cursor_jobs_by_job_id_rollback': Operation(
        operation_id='post_api_cursor_jobs_by_job_id_rollback',
        method='POST',
        path='/api/cursor/jobs/{job_id}/rollback',
        auth='session',
        tag='cognitive',
        summary='Cursor Rollback',
    ),
    'post_api_devagent_autorun': Operation(
        operation_id='post_api_devagent_autorun',
        method='POST',
        path='/api/devagent/autorun',
        auth='session',
        tag='devagent',
        summary='Api Devagent Autorun',
    ),
    'post_api_devagent_by_project_id_answer': Operation(
        operation_id='post_api_devagent_by_project_id_answer',
        method='POST',
        path='/api/devagent/{project_id}/answer',
        auth='session',
        tag='devagent',
        summary='Devagent Answer',
    ),
    'post_api_devagent_by_project_id_deploy': Operation(
        operation_id='post_api_devagent_by_project_id_deploy',
        method='POST',
        path='/api/devagent/{project_id}/deploy',
        auth='session',
        tag='devagent',
        summary='Api Devagent Deploy',
    ),
    'post_api_devagent_by_project_id_pause': Operation(
        operation_id='post_api_devagent_by_project_id_pause',
        method='POST',
        path='/api/devagent/{project_id}/pause',
        auth='session',
        tag='devagent',
        summary='Devagent Pause',
    ),
    'post_api_devagent_by_project_id_pr': Operation(
        operation_id='post_api_devagent_by_project_id_pr',
        method='POST',
        path='/api/devagent/{project_id}/pr',
        auth='session',
        tag='devagent',
        summary='Api Devagent Pr',
    ),
    'post_api_devagent_by_project_id_rebase': Operation(
        operation_id='post_api_devagent_by_project_id_rebase',
        method='POST',
        path='/api/devagent/{project_id}/rebase',
        auth='session',
        tag='devagent',
        summary='Api Devagent Rebase',
    ),
    'post_api_devagent_by_project_id_refactor': Operation(
        operation_id='post_api_devagent_by_project_id_refactor',
        method='POST',
        path='/api/devagent/{project_id}/refactor',
        auth='session',
        tag='devagent',
        summary='Api Devagent Refactor',
    ),
    'post_api_devagent_by_project_id_run': Operation(
        operation_id='post_api_devagent_by_project_id_run',
        method='POST',
        path='/api/devagent/{project_id}/run',
        auth='session',
        tag='devagent',
        summary='Devagent Run',
    ),
    'post_api_devagent_start': Operation(
        operation_id='post_api_devagent_start',
        method='POST',
        path='/api/devagent/start',
        auth='session',
        tag='devagent',
        summary='Devagent Start',
    ),
    'post_api_devices_by_device_id_activate': Operation(
        operation_id='post_api_devices_by_device_id_activate',
        method='POST',
        path='/api/devices/{device_id}/activate',
        auth='session',
        tag='devices',
        summary='Api Activate Device',
    ),
    'post_api_devices_by_device_id_heartbeat': Operation(
        operation_id='post_api_devices_by_device_id_heartbeat',
        method='POST',
        path='/api/devices/{device_id}/heartbeat',
        auth='device_token',
        tag='devices',
        summary='Api Device Heartbeat',
    ),
    'post_api_devices_by_device_id_revoke': Operation(
        operation_id='post_api_devices_by_device_id_revoke',
        method='POST',
        path='/api/devices/{device_id}/revoke',
        auth='session',
        tag='devices',
        summary='Api Revoke Device',
    ),
    'post_api_devices_by_device_id_screen': Operation(
        operation_id='post_api_devices_by_device_id_screen',
        method='POST',
        path='/api/devices/{device_id}/screen',
        auth='device_token',
        tag='devices',
        summary='Api Device Screen',
    ),
    'post_api_devices_by_device_id_token_rotate': Operation(
        operation_id='post_api_devices_by_device_id_token_rotate',
        method='POST',
        path='/api/devices/{device_id}/token/rotate',
        auth='session',
        tag='devices',
        summary='Api Rotate Device Token',
    ),
    'post_api_devices_pairing_start': Operation(
        operation_id='post_api_devices_pairing_start',
        method='POST',
        path='/api/devices/pairing/start',
        auth='session',
        tag='devices',
        summary='Api Start Device Pairing',
    ),
    'post_api_devices_register': Operation(
        operation_id='post_api_devices_register',
        method='POST',
        path='/api/devices/register',
        auth='pairing_code',
        tag='devices',
        summary='Api Register Device',
    ),
    'post_api_dnd': Operation(
        operation_id='post_api_dnd',
        method='POST',
        path='/api/dnd',
        auth='session',
        tag='dnd',
        summary='Api Dnd Enable',
    ),
    'post_api_email_watcher_catchup': Operation(
        operation_id='post_api_email_watcher_catchup',
        method='POST',
        path='/api/email-watcher/catchup',
        auth='session',
        tag='email-watcher',
        summary='Api Email Watcher Catchup',
    ),
    'post_api_fitness_advice': Operation(
        operation_id='post_api_fitness_advice',
        method='POST',
        path='/api/fitness/advice',
        auth='session',
        tag='fitness',
        summary='Generate Advice',
    ),
    'post_api_fitness_meals': Operation(
        operation_id='post_api_fitness_meals',
        method='POST',
        path='/api/fitness/meals',
        auth='session',
        tag='fitness',
        summary='Create Meal',
    ),
    'post_api_fitness_meals_from_photo': Operation(
        operation_id='post_api_fitness_meals_from_photo',
        method='POST',
        path='/api/fitness/meals/from-photo',
        auth='session',
        tag='fitness',
        summary='Create Meal From Photo',
    ),
    'post_api_fitness_meals_from_text': Operation(
        operation_id='post_api_fitness_meals_from_text',
        method='POST',
        path='/api/fitness/meals/from-text',
        auth='session',
        tag='fitness',
        summary='Create Meal From Text',
    ),
    'post_api_fitness_water': Operation(
        operation_id='post_api_fitness_water',
        method='POST',
        path='/api/fitness/water',
        auth='session',
        tag='fitness',
        summary='Add Water',
    ),
    'post_api_fitness_weights': Operation(
        operation_id='post_api_fitness_weights',
        method='POST',
        path='/api/fitness/weights',
        auth='session',
        tag='fitness',
        summary='Create Weight',
    ),
    'post_api_fitness_wellbeing': Operation(
        operation_id='post_api_fitness_wellbeing',
        method='POST',
        path='/api/fitness/wellbeing',
        auth='session',
        tag='fitness',
        summary='Create Wellbeing',
    ),
    'post_api_fitness_workouts': Operation(
        operation_id='post_api_fitness_workouts',
        method='POST',
        path='/api/fitness/workouts',
        auth='session',
        tag='fitness',
        summary='Create Workout',
    ),
    'post_api_food_cart_by_plan_id_confirm': Operation(
        operation_id='post_api_food_cart_by_plan_id_confirm',
        method='POST',
        path='/api/food/cart/{plan_id}/confirm',
        auth='session',
        tag='food',
        summary='Api Food Cart Confirm',
    ),
    'post_api_food_cart_prepare': Operation(
        operation_id='post_api_food_cart_prepare',
        method='POST',
        path='/api/food/cart/prepare',
        auth='session',
        tag='food',
        summary='Api Food Cart Prepare',
    ),
    'post_api_food_delivery_refresh': Operation(
        operation_id='post_api_food_delivery_refresh',
        method='POST',
        path='/api/food/delivery/refresh',
        auth='session',
        tag='food',
        summary='Api Food Delivery Refresh',
    ),
    'post_api_food_menus_refresh': Operation(
        operation_id='post_api_food_menus_refresh',
        method='POST',
        path='/api/food/menus/refresh',
        auth='session',
        tag='food',
        summary='Api Food Menus Refresh',
    ),
    'post_api_food_orders_by_order_id_rating': Operation(
        operation_id='post_api_food_orders_by_order_id_rating',
        method='POST',
        path='/api/food/orders/{order_id}/rating',
        auth='session',
        tag='food',
        summary='Api Food Rate Order',
    ),
    'post_api_food_selectors_reload': Operation(
        operation_id='post_api_food_selectors_reload',
        method='POST',
        path='/api/food/selectors/reload',
        auth='session',
        tag='food',
        summary='Api Food Selectors Reload',
    ),
    'post_api_food_session_capture': Operation(
        operation_id='post_api_food_session_capture',
        method='POST',
        path='/api/food/session/capture',
        auth='session',
        tag='food',
        summary='Api Food Session Capture',
    ),
    'post_api_food_session_probe': Operation(
        operation_id='post_api_food_session_probe',
        method='POST',
        path='/api/food/session/probe',
        auth='session',
        tag='food',
        summary='Api Food Session Probe',
    ),
    'post_api_food_settings_reset': Operation(
        operation_id='post_api_food_settings_reset',
        method='POST',
        path='/api/food/settings/reset',
        auth='session',
        tag='food',
        summary='Api Food Settings Reset',
    ),
    'post_api_food_suggestions_by_slot_order': Operation(
        operation_id='post_api_food_suggestions_by_slot_order',
        method='POST',
        path='/api/food/suggestions/{slot}/order',
        auth='session',
        tag='food',
        summary='Api Food Quick Order',
    ),
    'post_api_food_suggestions_generate': Operation(
        operation_id='post_api_food_suggestions_generate',
        method='POST',
        path='/api/food/suggestions/generate',
        auth='session',
        tag='food',
        summary='Api Food Suggestions Generate',
    ),
    'post_api_imessage_import_run': Operation(
        operation_id='post_api_imessage_import_run',
        method='POST',
        path='/api/imessage-import/run',
        auth='session',
        tag='imessage-import',
        summary='Api Imessage Import Run',
    ),
    'post_api_improvements_run': Operation(
        operation_id='post_api_improvements_run',
        method='POST',
        path='/api/improvements/run',
        auth='session',
        tag='cognitive',
        summary='Improvement Run',
    ),
    'post_api_jarvis_journal_generate': Operation(
        operation_id='post_api_jarvis_journal_generate',
        method='POST',
        path='/api/jarvis-journal/generate',
        auth='session',
        tag='jarvis-journal',
        summary='Api Jarvis Journal Generate',
    ),
    'post_api_journal': Operation(
        operation_id='post_api_journal',
        method='POST',
        path='/api/journal',
        auth='session',
        tag='journal',
        summary='Api Journal Post',
    ),
    'post_api_life_context': Operation(
        operation_id='post_api_life_context',
        method='POST',
        path='/api/life-context',
        auth='session',
        tag='life-context',
        summary='Api Life Context Create',
    ),
    'post_api_life_context_by_context_id_close': Operation(
        operation_id='post_api_life_context_by_context_id_close',
        method='POST',
        path='/api/life-context/{context_id}/close',
        auth='session',
        tag='life-context',
        summary='Api Life Context Close',
    ),
    'post_api_life_profile': Operation(
        operation_id='post_api_life_profile',
        method='POST',
        path='/api/life-profile',
        auth='session',
        tag='life-profile',
        summary='Api Life Profile Create',
    ),
    'post_api_location': Operation(
        operation_id='post_api_location',
        method='POST',
        path='/api/location',
        auth='mobile_or_location_token',
        tag='location',
        summary='Api Location Receive',
    ),
    'post_api_location_batch': Operation(
        operation_id='post_api_location_batch',
        method='POST',
        path='/api/location/batch',
        auth='mobile_or_location_token',
        tag='location',
        summary='Api Location Batch',
    ),
    'post_api_location_name_current': Operation(
        operation_id='post_api_location_name_current',
        method='POST',
        path='/api/location/name-current',
        auth='session',
        tag='location',
        summary='Api Location Name Current',
    ),
    'post_api_maintenance_run': Operation(
        operation_id='post_api_maintenance_run',
        method='POST',
        path='/api/maintenance/run',
        auth='session',
        tag='maintenance',
        summary='Api Maintenance Run',
    ),
    'post_api_migrations_run': Operation(
        operation_id='post_api_migrations_run',
        method='POST',
        path='/api/migrations/run',
        auth='session',
        tag='migrations',
        summary='Api Migrations Run',
    ),
    'post_api_mission_prompt': Operation(
        operation_id='post_api_mission_prompt',
        method='POST',
        path='/api/mission/prompt',
        auth='session',
        tag='mission',
        summary='Mission Prompt',
    ),
    'post_api_mobile_capabilities': Operation(
        operation_id='post_api_mobile_capabilities',
        method='POST',
        path='/api/mobile/capabilities',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Capabilities',
    ),
    'post_api_mobile_chat': Operation(
        operation_id='post_api_mobile_chat',
        method='POST',
        path='/api/mobile/chat',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Chat',
    ),
    'post_api_mobile_chat_confirm': Operation(
        operation_id='post_api_mobile_chat_confirm',
        method='POST',
        path='/api/mobile/chat/confirm',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Chat Confirm',
    ),
    'post_api_mobile_conversations': Operation(
        operation_id='post_api_mobile_conversations',
        method='POST',
        path='/api/mobile/conversations',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Create Conversation',
    ),
    'post_api_mobile_devices_by_device_id_revoke': Operation(
        operation_id='post_api_mobile_devices_by_device_id_revoke',
        method='POST',
        path='/api/mobile/devices/{device_id}/revoke',
        auth='session',
        tag='mobile',
        summary='Api Mobile Device Revoke',
    ),
    'post_api_mobile_pairing_complete': Operation(
        operation_id='post_api_mobile_pairing_complete',
        method='POST',
        path='/api/mobile/pairing/complete',
        auth='pairing_code',
        tag='mobile',
        summary='Api Mobile Pairing Complete',
    ),
    'post_api_mobile_pairing_start': Operation(
        operation_id='post_api_mobile_pairing_start',
        method='POST',
        path='/api/mobile/pairing/start',
        auth='session',
        tag='mobile',
        summary='Api Mobile Pairing Start',
    ),
    'post_api_mobile_push_token': Operation(
        operation_id='post_api_mobile_push_token',
        method='POST',
        path='/api/mobile/push-token',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Push Token',
    ),
    'post_api_mobile_session': Operation(
        operation_id='post_api_mobile_session',
        method='POST',
        path='/api/mobile/session',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Session',
    ),
    'post_api_mobile_voice_turn': Operation(
        operation_id='post_api_mobile_voice_turn',
        method='POST',
        path='/api/mobile/voice/turn',
        auth='mobile_bearer',
        tag='mobile',
        summary='Api Mobile Voice Turn',
    ),
    'post_api_notifications_by_notif_id_read': Operation(
        operation_id='post_api_notifications_by_notif_id_read',
        method='POST',
        path='/api/notifications/{notif_id}/read',
        auth='session',
        tag='notifications',
        summary='Api Notifications Mark Read',
    ),
    'post_api_notifications_read_all': Operation(
        operation_id='post_api_notifications_read_all',
        method='POST',
        path='/api/notifications/read-all',
        auth='session',
        tag='notifications',
        summary='Api Notifications Mark All Read',
    ),
    'post_api_people': Operation(
        operation_id='post_api_people',
        method='POST',
        path='/api/people',
        auth='session',
        tag='people',
        summary='Api People Upsert',
    ),
    'post_api_people_by_name_ask': Operation(
        operation_id='post_api_people_by_name_ask',
        method='POST',
        path='/api/people/{name}/ask',
        auth='session',
        tag='people',
        summary='Api People Ask',
    ),
    'post_api_people_by_name_description_refresh': Operation(
        operation_id='post_api_people_by_name_description_refresh',
        method='POST',
        path='/api/people/{name}/description/refresh',
        auth='session',
        tag='people',
        summary='Api Person Description Refresh',
    ),
    'post_api_people_by_name_remind': Operation(
        operation_id='post_api_people_by_name_remind',
        method='POST',
        path='/api/people/{name}/remind',
        auth='session',
        tag='people',
        summary='Api Person Remind',
    ),
    'post_api_people_by_name_send': Operation(
        operation_id='post_api_people_by_name_send',
        method='POST',
        path='/api/people/{name}/send',
        auth='session',
        tag='people',
        summary='Api Person Send Imessage',
    ),
    'post_api_people_by_name_suggest_message': Operation(
        operation_id='post_api_people_by_name_suggest_message',
        method='POST',
        path='/api/people/{name}/suggest-message',
        auth='session',
        tag='people',
        summary='Api Person Suggest Message',
    ),
    'post_api_people_by_name_timeline_regenerate': Operation(
        operation_id='post_api_people_by_name_timeline_regenerate',
        method='POST',
        path='/api/people/{name}/timeline/regenerate',
        auth='session',
        tag='people',
        summary='Api Person Timeline Regenerate',
    ),
    'post_api_places': Operation(
        operation_id='post_api_places',
        method='POST',
        path='/api/places',
        auth='session',
        tag='places',
        summary='Api Places Create',
    ),
    'post_api_push_subscribe': Operation(
        operation_id='post_api_push_subscribe',
        method='POST',
        path='/api/push/subscribe',
        auth='session',
        tag='push',
        summary='Api Push Subscribe',
    ),
    'post_api_push_unsubscribe': Operation(
        operation_id='post_api_push_unsubscribe',
        method='POST',
        path='/api/push/unsubscribe',
        auth='session',
        tag='push',
        summary='Api Push Unsubscribe',
    ),
    'post_api_quality_ci_install_hook': Operation(
        operation_id='post_api_quality_ci_install_hook',
        method='POST',
        path='/api/quality/ci/install-hook',
        auth='session',
        tag='quality',
        summary='Api Quality Ci Install Hook',
    ),
    'post_api_quality_ci_run': Operation(
        operation_id='post_api_quality_ci_run',
        method='POST',
        path='/api/quality/ci/run',
        auth='session',
        tag='quality',
        summary='Api Quality Ci Run',
    ),
    'post_api_quality_duplicates_scan': Operation(
        operation_id='post_api_quality_duplicates_scan',
        method='POST',
        path='/api/quality/duplicates/scan',
        auth='session',
        tag='quality',
        summary='Api Quality Duplicates Scan',
    ),
    'post_api_quality_security_by_finding_id_fix': Operation(
        operation_id='post_api_quality_security_by_finding_id_fix',
        method='POST',
        path='/api/quality/security/{finding_id}/fix',
        auth='session',
        tag='quality',
        summary='Api Quality Security Fix',
    ),
    'post_api_quality_security_scan': Operation(
        operation_id='post_api_quality_security_scan',
        method='POST',
        path='/api/quality/security/scan',
        auth='session',
        tag='quality',
        summary='Api Quality Security Scan',
    ),
    'post_api_quality_tests_generate': Operation(
        operation_id='post_api_quality_tests_generate',
        method='POST',
        path='/api/quality/tests/generate',
        auth='session',
        tag='quality',
        summary='Api Quality Generate Tests',
    ),
    'post_api_recordings_by_recording_id_speakers_by_label_assign': Operation(
        operation_id='post_api_recordings_by_recording_id_speakers_by_label_assign',
        method='POST',
        path='/api/recordings/{recording_id}/speakers/{label}/assign',
        auth='session',
        tag='recordings',
        summary='Api Recording Assign Speaker',
    ),
    'post_api_rituals_by_ritual_run': Operation(
        operation_id='post_api_rituals_by_ritual_run',
        method='POST',
        path='/api/rituals/{ritual}/run',
        auth='session',
        tag='rituals',
        summary='Api Rituals Run',
    ),
    'post_api_scheduler_jobs_by_job_id_run': Operation(
        operation_id='post_api_scheduler_jobs_by_job_id_run',
        method='POST',
        path='/api/scheduler/jobs/{job_id}/run',
        auth='session',
        tag='scheduler',
        summary='Api Scheduler Job Run',
    ),
    'post_api_self_healing_diagnose': Operation(
        operation_id='post_api_self_healing_diagnose',
        method='POST',
        path='/api/self-healing/diagnose',
        auth='session',
        tag='self-healing',
        summary='Api Self Healing Diagnose',
    ),
    'post_api_task_candidates_by_candidate_id_decision': Operation(
        operation_id='post_api_task_candidates_by_candidate_id_decision',
        method='POST',
        path='/api/task-candidates/{candidate_id}/decision',
        auth='session',
        tag='task-control',
        summary='Decide Task Candidate',
    ),
    'post_api_task_control_tasks': Operation(
        operation_id='post_api_task_control_tasks',
        method='POST',
        path='/api/task-control/tasks',
        auth='session',
        tag='task-control',
        summary='Create Control Task',
    ),
    'post_api_task_control_tasks_by_task_id_approvals_by_approval_id_decision': Operation(
        operation_id='post_api_task_control_tasks_by_task_id_approvals_by_approval_id_decision',
        method='POST',
        path='/api/task-control/tasks/{task_id}/approvals/{approval_id}/decision',
        auth='session',
        tag='task-control',
        summary='Decide Control Approval',
    ),
    'post_api_task_control_tasks_by_task_id_cancel': Operation(
        operation_id='post_api_task_control_tasks_by_task_id_cancel',
        method='POST',
        path='/api/task-control/tasks/{task_id}/cancel',
        auth='session',
        tag='task-control',
        summary='Cancel Control Task',
    ),
    'post_api_task_control_tasks_by_task_id_comments': Operation(
        operation_id='post_api_task_control_tasks_by_task_id_comments',
        method='POST',
        path='/api/task-control/tasks/{task_id}/comments',
        auth='session',
        tag='task-control',
        summary='Add Control Comment',
    ),
    'post_api_task_control_tasks_by_task_id_plan': Operation(
        operation_id='post_api_task_control_tasks_by_task_id_plan',
        method='POST',
        path='/api/task-control/tasks/{task_id}/plan',
        auth='session',
        tag='task-control',
        summary='Plan Control Task',
    ),
    'post_api_task_control_tasks_by_task_id_plans_by_version_decision': Operation(
        operation_id='post_api_task_control_tasks_by_task_id_plans_by_version_decision',
        method='POST',
        path='/api/task-control/tasks/{task_id}/plans/{version}/decision',
        auth='session',
        tag='task-control',
        summary='Decide Control Plan',
    ),
    'post_api_tasks': Operation(
        operation_id='post_api_tasks',
        method='POST',
        path='/api/tasks',
        auth='session',
        tag='tasks',
        summary='Api Tasks Create',
    ),
    'post_upload': Operation(
        operation_id='post_upload',
        method='POST',
        path='/upload',
        auth='session',
        tag='upload',
        summary='Upload',
    ),
    'put_api_fitness_sessions_by_session_id_progress': Operation(
        operation_id='put_api_fitness_sessions_by_session_id_progress',
        method='PUT',
        path='/api/fitness/sessions/{session_id}/progress',
        auth='session',
        tag='fitness',
        summary='Update Session Progress',
    ),
    'put_api_life_profile_by_entry_id': Operation(
        operation_id='put_api_life_profile_by_entry_id',
        method='PUT',
        path='/api/life-profile/{entry_id}',
        auth='session',
        tag='life-profile',
        summary='Api Life Profile Update',
    ),
    'put_api_places_by_place_id': Operation(
        operation_id='put_api_places_by_place_id',
        method='PUT',
        path='/api/places/{place_id}',
        auth='session',
        tag='places',
        summary='Api Places Update',
    ),
    'put_api_privacy_documents': Operation(
        operation_id='put_api_privacy_documents',
        method='PUT',
        path='/api/privacy/documents',
        auth='session',
        tag='privacy',
        summary='Api Document Privacy Update',
    ),
}

OPERATIONS: Mapping[str, Operation] = MappingProxyType(_OPERATIONS)
