#!/usr/bin/env python3
"""Génère et contrôle les locks Python 3.12 hashés de JARVIS."""

from __future__ import annotations

import argparse
import hashlib
import platform as runtime_platform
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_DIR = ROOT / "requirements" / "locks"
UV_VERSION = "0.11.29"


@dataclass(frozen=True)
class LockProfile:
    name: str
    inputs: tuple[str, ...]
    tracked_sources: tuple[str, ...]
    platform: str | None
    output: str


PROFILES = {
    profile.name: profile
    for profile in (
        LockProfile(
            "production-linux",
            ("requirements.txt",),
            ("requirements.txt",),
            "x86_64-unknown-linux-gnu",
            "production-linux-x86_64-py312.txt",
        ),
        LockProfile(
            "production-macos",
            ("requirements.txt",),
            ("requirements.txt",),
            "aarch64-apple-darwin",
            "production-macos-arm64-py312.txt",
        ),
        LockProfile(
            "ci-linux",
            ("requirements-ci.txt",),
            ("requirements-ci.txt",),
            "x86_64-unknown-linux-gnu",
            "ci-linux-x86_64-py312.txt",
        ),
        LockProfile(
            "dev-macos",
            ("requirements-dev.txt",),
            ("requirements.txt", "requirements-dev.txt"),
            "aarch64-apple-darwin",
            "dev-macos-arm64-py312.txt",
        ),
        LockProfile(
            "agent-macos",
            ("requirements-agent.txt",),
            ("requirements-agent.txt",),
            "aarch64-apple-darwin",
            "agent-macos-arm64-py312.txt",
        ),
        LockProfile(
            "mlx-macos",
            ("requirements-mlx.txt",),
            ("requirements-mlx.txt",),
            None,
            "mlx-macos-arm64-py312.txt",
        ),
    )
}


def _source_digest(profile: LockProfile) -> str:
    digest = hashlib.sha256()
    for relative in profile.tracked_sources:
        path = ROOT / relative
        digest.update(relative.encode())
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _header(profile: LockProfile) -> str:
    sources = ",".join(profile.tracked_sources)
    target = profile.platform or "host-macos-arm64-14plus"
    return (
        "# AUTOGENERATED: do not edit by hand.\n"
        f"# lock-profile: {profile.name}\n"
        "# python-version: 3.12\n"
        f"# python-platform: {target}\n"
        f"# uv-version: {UV_VERSION}\n"
        f"# sources: {sources}\n"
        f"# source-sha256: {_source_digest(profile)}\n"
        "# update: python tools/update_python_locks.py\n\n"
    )


def _assert_uv_version() -> None:
    version = subprocess.run(
        ["uv", "--version"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if version.split()[:2] != ["uv", UV_VERSION]:
        raise SystemExit(f"uv {UV_VERSION} requis, trouvé: {version}")


def _validate_hashed_entries(path: Path) -> list[str]:
    lines = path.read_text().splitlines()
    errors: list[str] = []
    starts = [
        index
        for index, line in enumerate(lines)
        if line and not line[0].isspace() and not line.startswith(("#", "-"))
    ]
    for offset, start in enumerate(starts):
        end = starts[offset + 1] if offset + 1 < len(starts) else len(lines)
        requirement = lines[start]
        block = "\n".join(lines[start:end])
        if "==" not in requirement:
            errors.append(f"{path.name}:{start + 1}: dépendance non épinglée: {requirement}")
        if "--hash=sha256:" not in block:
            errors.append(f"{path.name}:{start + 1}: hash absent: {requirement}")
    if not starts:
        errors.append(f"{path.name}: lock vide")
    return errors


def check_profile(profile: LockProfile) -> list[str]:
    output = LOCK_DIR / profile.output
    if not output.is_file():
        return [f"{profile.name}: lock absent: {output.relative_to(ROOT)}"]

    text = output.read_text()
    expected = _header(profile)
    errors: list[str] = []
    if not text.startswith(expected):
        errors.append(
            f"{profile.name}: sources ou métadonnées modifiées; régénérer avec "
            "python tools/update_python_locks.py"
        )
    errors.extend(_validate_hashed_entries(output))
    return errors


def generate_profile(
    profile: LockProfile,
    *,
    upgrade: bool,
    upgrade_packages: list[str],
) -> None:
    if profile.platform is None:
        major_version = int(runtime_platform.mac_ver()[0].split(".")[0] or "0")
        if runtime_platform.system() != "Darwin" or runtime_platform.machine() != "arm64":
            raise SystemExit("le lock MLX doit être généré sur macOS Apple Silicon")
        if major_version < 14:
            raise SystemExit("le lock MLX exige macOS 14 ou plus récent")

    LOCK_DIR.mkdir(parents=True, exist_ok=True)
    output = LOCK_DIR / profile.output
    with tempfile.NamedTemporaryFile(
        prefix=f".{profile.name}-",
        suffix=".txt",
        dir=LOCK_DIR,
        delete=False,
    ) as handle:
        temporary = Path(handle.name)

    try:
        if output.exists() and not upgrade:
            shutil.copyfile(output, temporary)
        command = [
            "uv",
            "pip",
            "compile",
            *(str(ROOT / source) for source in profile.inputs),
            "--python-version",
            "3.12",
            "--generate-hashes",
            "--no-header",
            "--no-progress",
            "--output-file",
            str(temporary),
        ]
        if profile.platform:
            command.extend(("--python-platform", profile.platform))
        if upgrade:
            command.append("--upgrade")
        for package in upgrade_packages:
            command.extend(("--upgrade-package", package))
        subprocess.run(command, cwd=ROOT, check=True)
        resolved = temporary.read_text()
        temporary.write_text(_header(profile) + resolved)
        errors = _validate_hashed_entries(temporary)
        if errors:
            raise SystemExit("\n".join(errors))
        temporary.replace(output)
        print(f"generated {output.relative_to(ROOT)}")
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("profiles", nargs="*", choices=sorted(PROFILES))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--upgrade", action="store_true")
    parser.add_argument("--upgrade-package", action="append", default=[])
    args = parser.parse_args()
    selected = args.profiles or list(PROFILES)

    if args.check:
        errors = [
            error
            for name in selected
            for error in check_profile(PROFILES[name])
        ]
        if errors:
            print("\n".join(errors))
            return 1
        print(f"{len(selected)} locks Python vérifiés")
        return 0

    _assert_uv_version()
    for name in selected:
        generate_profile(
            PROFILES[name],
            upgrade=args.upgrade,
            upgrade_packages=args.upgrade_package,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
